tags:
  name: Friend
  description: 친구관리 관련 API

/app/friend:
  get:
    summary: API NO.1 - userId 받아서 친구목록 조회 api
    # parameters:
    #   - name: userIdx
    #     in: query
    #     required: true
    #     description: userIdx를 입력하세요.
    #     schema:
    #       type: integer
    description: jwt토큰으로 유저의 친구 수와 친구 목록 반환
    tags:
      - Dictionary
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                friendCount:
                  type: arrya
                  items:
                    type: int
                    description: 친구 수
                popularKeywords:
                  type: array
                  items:
                    type: string
                    description: 친구 목록
      '2012':
        description: jwt토큰 불일치