tags:
  name: Friend
  description: 친구관리 관련 API

/app/friend:
  get:
    summary: API NO.1 - userId 받아서 친구목록 조회 api
    # parameters:
    #   - name: userIdx
    #     in: query
    #     required: true
    #     description: userIdx를 입력하세요.
    #     schema:
    #       type: integer
    description: jwt토큰으로 유저의 친구 수와 친구 목록 반환
    tags:
      - Friend
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                friendCount:
                  type: arrya
                  items:
                    type: int
                    description: 친구 수
                popularKeywords:
                  type: array
                  items:
                    type: string
                    description: 친구 목록
      '2012':
        description: jwt토큰 불일치

/app/friend/searchUser:
  post:
    summary: API NO.2 - 검색 단어와 연관된 닉네임 가진 user 조회 api
    description: search에 사 단어 넣으면 userNickname에 search 단어 들어간 모든 userNickname return
    tags:
      - Friend
    #operationId: searchUser
    parameters:
      - name: search
        in: query
        required: true
        description: 검색 내용
        schema:
          type: string
    responses:
      '1000':
        description: 성공
      '606':
        description: 검색내용을 입력해 주세요.

/app/friend/addFriend:
  post:
    summary: API NO.3 - 친구 신청(추가)기능 api
    description: 내 입장에선 보냄 상대 입장에서는 받음 - 나(fromUserIdx), 상대(toUserIdx)
    tags:
      - Friend
    #operationId: addFriend
    parameters:
      - name: friendIdx
        in: path
        required: true
        description: 신청 보낼 유저의 userIdx
        schema:
          type: integer
    responses:
      '1000':
        description: 성공
      '2013':
        description: jwt토큰 검증오류.

/app/friend/addFriendList:
  get:
    summary: API NO.3.1 - 보낸 친구신청 목록 get api
    description: toUserIdx, toUserIdx의 userNickname get
    tags:
      - Friend
    #operationId: addFriendList
    responses:
      '1000':
        description: 성공
      '2013':
        description: jwt토큰 검증오류.

/app/friend/cancelAdd:
  delete:
    summary: API NO.3.2 - 보낸 친구신청 취소 api
    description: api no.3.1에서 불러온 friendListIdx 입력
    tags:
      - Friend
    #operationId: cancelAdd
    parameters:
      - name: friendListIdx
        in: query
        required: true
        description: 삭제할 친구신청 목록
        schema:
          type: integer
    responses:
      '1000':
        description: 성공
      '2013':
        description: jwt토큰 검증오류.

/app/friend/getReceiveList:
  get:
    summary: API NO.4 - 받은 친구신청 목록 get api
    description: friendListIdx get(뒤에서 씀)
    tags:
      - Friend
    #operationId: getReceiveList
    responses:
      '1000':
        description: 성공
      '2013':
        description: jwt토큰 검증오류.