tags:
  name: Process
  description: 운동 과정 관련 API - 박준규

/app/process/:
  get:
    tags:
      - Process
    summary: 운동 루틴 조회 API
    description: 하루의 루틴을 조회하는 API
    parameters:
      - name: dayOfWeek
        in: query
        required: true
        description: dayOfweek를 입력하세요.
        schema:
          type: string
          example: 'tue'
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  example: true
                'code':
                  type: integer
                  example: 1000
                'message':
                  type: string
                  example: '성공'
                'result':
                  type: object
                  properties:
                    routineDetails:
                      type: array
                      items:
                        type: object
                        properties:
                          exerciseInfo:
                            type: object
                            properties:
                              healthCategoryIdx:
                                type: integer
                                example: 3
                              exerciseName:
                                type: string
                                example: '체스트 프레스 머신'
                              rest:
                                type: integer
                                example: 30
                          totalSets:
                            type: integer
                            example: 2
                          rep:
                            type: integer
                            example: 5
                          weight:
                            type: integer
                            example: 70
                          predictTime:
                            type: integer
                            example: 300
                          predictCalories:
                            type: integer
                            example: 20
                          sets:
                            type: array
                            items:
                              type: object
                              properties:
                                set:
                                  type: integer
                                  example: 0
                                rep:
                                  type: integer
                                  example: 5
                                weight:
                                  type: integer
                                  example: 4
                    totalDuration:
                      type: integer
                      example: 5
                    totalCalories:
                      type: integer
                      example: 28
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패


/app/process/replace/{routineIdx}:
  get:
    tags:
      - Process
    summary: 운동 루틴 대체 추천 조회 API
    description: 같은 부위 중 랜덤으로 최대 3가지 추천
    parameters:
      - name: routineIdx
        in: path
        required: true
        description: 운동 루틴 인덱스(오늘 운동 리스트들)
        schema:
          type: integer
    responses:
      '1000':
        description: 성공 - 같은 부위 중 랜덤으로 3가지를 배열로 반환
        content:
          application/json:
            schema:
              type: object
              properties:
                isSuccess:
                  type: boolean
                  example: true
                code:
                  type: integer
                  example: 1000
                message:
                  type: string
                  example: 성공
                result:
                  type: object
                  properties:
                    replacementRecommendations:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            example: 체스트 프레스 머신
                          healthCategoryIdx:
                            type: integer
                            example: 3
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패

  patch:
    tags:
      - Process
    summary: 대체된 운동 정보 업데이트 API
    description: 대체된 운동 정보를 수정합니다.
    parameters:
      - in: path
        name: routineIdx
        required: true
        description: 운동 루틴 인덱스
        schema:
          type: integer
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              beforeHealthCategoryIdx:
                type: integer
                example: 1
              afterHealthCategoryIdx:
                type: integer
                example: 2
    responses:
      '1000':
        description: 성공 - 대체된 운동 정보가 업데이트되었습니다.
        content:
          application/json:
            schema:
              type: object
              properties:
                isSuccess:
                  type: boolean
                  example: true
                code:
                  type: integer
                  example: 1000
                message:
                  type: string
                  example: 성공
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패




/app/process/{routineIdx}:
  patch:
    tags:
      - Process
    summary: 운동 건너뛰기 API
    parameters:
      - in: path
        name: routineIdx
        required: true
        description: 루틴 인덱스
        schema:
          type: integer
      - in: body
        name: body
        required: true
        description: 요청 바디
        schema:
          type: object
          properties:
            healthCategoryIdx:
              type: integer
              description: 건너뛸 운동 카테고리 인덱스
            dayOfWeek:
              type: string
              description: 요일 (mon, tue, wed, thu, fri, sat, sun)
    responses:
      '1000':
        description: 운동 건너뛰기 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                isSuccess:
                  type: boolean
                  description: 성공 여부
                code:
                  type: string
                  description: 응답 코드
                message:
                  type: string
                  description: 응답 메시지
                result:
                  type: string
                  description: 건너뛴 운동 이름



/process/end/{routineIdx}:
  post:
    summary: "myCalendar 기록 추가 API"
    tags:
      - "Process"
    parameters:
      - name: routineIdx
        in: path
        required: true
        type: integer
        description: "Routine index"
      - in: body
        name: totalExerciseTime
        required: true
        schema:
          type: object
          properties:
            totalExerciseTime:
              type: integer
              description: "총 운동 시간을 분 단위로 써주세요."
    responses:
      '1000':
        description: "성공! myCalendar에 기록되었습니다."
        schema:
          type: object
          properties:
            status:
              type: string
              example: "success"
            data:
              type: object
              properties:
                myCalendarId:
                  type: integer
                  example: 123
                userId:
                  type: integer
                  example: 456
                routineIdx:
                  type: integer
                  example: 789
                totalWeight:
                  type: integer
                  example: 150
                totalExerciseTime:
                  type: integer
                  example: 60
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패