tags:
  name: Process
  description: 운동 과정 관련 API - 박준규

/app/process/:
  get:
    tags:
      - Process
    summary: 운동 루틴 조회 API
    description: 하루의 루틴을 조회하는 API
    parameters:
      - name: dayOfWeek
        in: path
        required: true
        description: 오늘 요일을 쓰세요.
        schema:
          type: string
          example: '화요일'
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  example: true
                'code':
                  type: integer
                  example: 1000
                'message':
                  type: string
                  example: '성공'
                'result':
                  type: object
                  properties:
                    routineDetails:
                      type: array
                      items:
                        type: object
                        properties:
                          exerciseInfo:
                            type: object
                            properties:
                              healthCategoryIdx:
                                type: integer
                                example: 3
                              exerciseName:
                                type: string
                                example: '체스트 프레스 머신'
                              rest:
                                type: integer
                                example: 30
                          totalSets:
                            type: integer
                            example: 2
                          rep0:
                            type: integer
                            example: 5
                          weight0:
                            type: integer
                            example: 70
                          predictTime:
                            type: integer
                            example: 300
                          predictCalories:
                            type: integer
                            example: 20
                          sets:
                            type: array
                            items:
                              type: object
                              properties:
                                set:
                                  type: integer
                                  example: 0
                                rep:
                                  type: integer
                                  example: 5
                                weight:
                                  type: integer
                                  example: 4
                    totalDuration:
                      type: integer
                      example: 5
                    totalCalories:
                      type: integer
                      example: 28
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패


/app/process/replace/{detailIdx}:
  get:
    tags:
      - Process
    summary: 운동 루틴 대체 추천 조회 API
    description: 같은 부위 중 랜덤으로 최대 3가지 추천
    response:
      '1000':
        description: 성공 - 같은 부위 중 랜덤으로 3가지를 배열로 반환
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  example: '성공'
                result:
                  type: array
                  items:
                    type: object
                    properties:
                      routineDetailIdx:
                        type: integer
                        example: 2
                      exerciseDetails:
                        type: array
                        items:
                          type: object
                          properties:
                            healthCategoryIdx:
                              type: integer
                              example: 3
                            exerciseName:
                              type: string
                              example: 'Chest Press Machine'
                      sets:
                        type: array
                        items:
                          type: object
                          properties:
                            set:
                              type: integer
                              example: 0
                            rep:
                              type: integer
                              example: 5
                            weight:
                              type: integer
                              example: 70
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패

/app/process/replace/exercise:
  patch:
    tags:
      - Process
    summary: 대체 운동 수정 API
    description: myRoutine에 수정된 걸로 반영
    response:
      '1000':
        description: 수정 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  exapmle:

/app/process/{routineDetailIdx}:
  patch:
    tags:
      - Process
    summary: 운동 스킵 API
    description: 현재 운동은 모두(세트 등) 스킵
    response:
      '1000':
        description: 수정 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  exapmle:
