tags:
  name: Process
  description: 운동 과정 관련 API - 박준규

/app/process:
  get:
    tags:
      - Process
    summary: 운동 루틴 조회 API
    description: 하루의 루틴을 조회하는 API, 요일을 영어로 앞의 세 글자를 입력해주세요.
    parameters:
      - name: dayOfWeek
        in: query
        required: true
        description: dayOfweek를 입력하세요.
        schema:
          type: string
          example: 'tue'
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  example: true
                'code':
                  type: integer
                  example: 1000
                'message':
                  type: string
                  example: '성공'
                'result':
                  type: object
                  properties:
                    $ref: '#/components/schemas/Routine'
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패


/app/process/replace/{routineIdx}:
  get:
    tags:
      - Process
    summary: 운동 루틴 대체 추천 조회 API
    description: 같은 부위 중 랜덤으로 최대 3가지 추천
    parameters:
      - name: routineIdx
        in: path
        required: true
        description: 운동 루틴 인덱스(오늘 운동 리스트들)
        schema:
          type: integer
          example: 3
      - name: healthCategoryIdx
        in: query
        required: true
        description: 운동 명칭 인덱스
        schema:
          type: integer
          example: 14
    responses:
      '1000':
        description: 성공 - 같은 부위 중 랜덤으로 3가지를 배열로 반환
        content:
          application/json:
            schema:
              type: object
              properties:
                isSuccess:
                  type: boolean
                  example: true
                code:
                  type: integer
                  example: 1000
                message:
                  type: string
                  example: 성공
                result:
                  type: object
                  properties:
                    replacementRecommendations:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            example: 체스트 프레스 머신
                          healthCategoryIdx:
                            type: integer
                            example: 3
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패

  patch:
    tags:
      - Process
    summary: 대체된 운동 정보 업데이트 API
    description: 대체된 운동 정보를 수정합니다. 대체된 운동에 대한 이름과 Idx를 발급합니다.
    parameters:
      - in: path
        name: routineIdx
        required: true
        description: 운동 루틴 인덱스
        schema:
          type: integer
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              beforeHealthCategoryIdx:
                type: integer
                example: 1
              afterHealthCategoryIdx:
                type: integer
                example: 2
    responses:
      '1000':
        description: 성공 - 대체된 운동 정보가 업데이트되었습니다.
        content:
          application/json:
            schema:
              type: object
              properties:
                isSuccess:
                  type: boolean
                  example: true
                code:
                  type: integer
                  example: 1000
                message:
                  type: string
                  example: 성공
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패




/app/process/{routineIdx}:
  patch:
    tags:
      - Process
    summary: 운동 건너뛰기 API
    description: 건너뛰기를 통해 마지막 운동 결과 조회에서 표시가 됩니다.
    parameters:
      - in: path
        name: routineIdx
        required: true
        description: 오늘 루틴 리스트들을 가지고 있는 routineIdx를 입력해주세요.
        schema:
          type: integer
      - in: body
        name: body
        required: true
        description: 수정할 운동(healthCategoryIdx)과 요일(dayOfWeek)을 입력해주세요.
        schema:
          type: object
          properties:
            healthCategoryIdx:
              type: integer
              description: 건너뛸 운동(healthCategoryIdx)
            dayOfWeek:
              type: string
              description: 요일 (mon, tue, wed, thu, fri, sat, sun)
    responses:
      '1000':
        description: 운동 건너뛰기 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                isSuccess:
                  type: boolean
                  description: 성공 여부
                code:
                  type: string
                  description: 응답 코드
                message:
                  type: string
                  description: 응답 메시지
                result:
                  type: string
                  description: 건너뛴 운동 이름



/process/end/{routineIdx}:
  post:
    summary: "myCalendar 기록 추가 API"
    description: 운동 기록을 마이 캘린더에 저장합니다. 초 단위로 입력해주세요.
    tags:
      - "Process"
    parameters:
      - name: routineIdx
        in: path
        required: true
        type: integer
        description: "Routine index"
      - in: body
        name: totalExerciseTime
        required: true
        schema:
          type: object
          properties:
            totalExerciseTime:
              type: integer
              description: "총 운동 시간을 초 단위로 써주세요."
    responses:
      '1000':
        description: "성공! myCalendar에 기록되었습니다."
        schema:
          type: object
          properties:
            status:
              type: string
              example: "success"
            data:
              type: object
              properties:
                myCalendarId:
                  type: integer
                  example: 123
                userId:
                  type: integer
                  example: 456
                routineIdx:
                  type: integer
                  example: 789
                totalWeight:
                  type: integer
                  example: 150
                totalExerciseTime:
                  type: integer
                  example: 60
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패


/app/process/end:
  get:
    tags:
      - Process
    summary: 결과 조회 API
    description: skip 포함해서 최종 운동 데이터 조회 및 일주일 전 데이터 증감, 한 달 동안 운동횟수 조회 API
    parameters:
      - in: query
        name: dayOfWeek
        schema:
          type: string
        description: 조회할 요일 (mon, tue ...)
    responses:
      '1000':
        description: 성공적으로 결과 데이터를 조회한 경우
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  example: true
                'code':
                  type: string
                  example: 1000
                'message':
                  type: string
                  example: '성공'
                'result':
                  type: object
                  properties:
                    updateRoutine:
                      $ref: '#/components/schemas/Routine'
                    getComparison:
                      $ref: '#/components/schemas/Comparison'
                    countHealth:
                      $ref: '#/components/schemas/HealthCount'
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패                

components:
  schemas:
    Routine:
      type: object
      properties:
        dayOfWeek:
          type: string
          description: 요일
        routineIdx:
          type: integer
          description: 루틴 인덱스
        routineDetails:
          type: array
          items:
            type: object
            properties:
              exerciseInfo:
                $ref: '#/components/schemas/ExerciseInfo'
              skip:
                type: boolean
                description: 해당 운동 스킵 여부
              totalSets:
                type: integer
                description: 총 세트 수
              rep:
                type: integer
                description: 횟수
              weight:
                type: float
                description: 무게
              predictTime:
                type: integer
                description: 예상 운동 시간 (초)
              predictCalories:
                type: integer
                description: 예상 소모 칼로리
              exerciseWeight:
                type: float
                description: 총 운동 무게
              rest:
                type: integer
                description: 휴식 시간 (초)
              sets:
                type: array
                items:
                  type: object
                  properties:
                    set:
                      type: integer
                      description: 세트 순서
                    rep:
                      type: integer
                      description: 세트당 운동 횟수
                    weight:
                      type: integer
                      description: 세트당 무게
      ExerciseInfo:
        type: object
        properties:
          healthCategoryIdx:
            type: integer
            description: 운동 카테고리 인덱스
          exerciseName:
            type: string
            description: 운동 이름
          parts:
            type: string
            description: 부위
          muscle:
            type: string
            description: 근육
          equipment:
            type: string
            description: 운동기구
          caution:
            type: string
            description: 주의사항
