tags:
  name: Process
  description: 운동 과정 관련 API - 박준규

/app/process/{routineIdx}:
  get:
    tags:
      - Process
    summary: 운동 루틴 조회 API
    description: 하루의 루틴을 조회하는 API
    parameters:
      - name: routineIdx
        in: path
        required: true
        description: 해당 루틴 Idx를 입력하세요.
        schema:
          type: integer
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  example: true
                'code':
                  type: integer
                  example: 1000
                'message':
                  type: string
                  example: '성공'
                'result':
                  $ref: '#/components/schemas/Routine'
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패

/app/process/before/{routineIdx}:
  get:
    tags:
      - Process
    summary: 운동 시작 전 루틴 조회 API
    description: 세트, 무게, 횟수 확인하는 운동 루틴 세부사항 API
    parameters:
      - name: routineIdx
        in: path
        required: true
        description: 루틴 Idx를 입력하세요.
        schema:
          type: integer
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                isSuccess:
                  type: boolean
                  example: true
                code:
                  type: integer
                  example: 1000
                message:
                  type: string
                  example: '성공'
                result:
                  type: array
                  items:
                    type: object
                    properties:
                      routineDetailIdx:
                        type: integer
                        example: 2
                      all_set:
                        type: string
                        example: "3"
                      data_rep0:
                        type: integer
                        example: 5
                      data_weight0:
                        type: integer
                        example: 70
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패


/app/process/detail/{routineIdx}:
  get:
    tags:
      - Process
    summary: 운동 과정 중 루틴 조회 API
    description: 운동 과정 중 현재 진행하는 세트 조회 API
    responses:
      '1000':
        description: 성공 - 총 세트 수와 첫 번째 무게와 횟수를 반환합니다.
        content:
          application/json:
            schema:
              type: object
              properties:
                isSuccess:
                  type: boolean
                  example: true
                code:
                  type: integer
                  example: 1000
                message:
                  type: string
                  example: '성공'
                result:
                  type: array
                  items:
                    type: object
                    properties:
                      healthCategoryIdx:
                        type: integer
                        example: 3
                      content:
                        type: array
                        items:
                          type: object
                          properties:
                            rep:
                              type: integer
                              example: 5
                            weight:
                              type: integer
                              example: 70
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패


/app/process/replace/{detailIdx}:
  get:
    tags:
      - Process
    summary: 운동 루틴 대체 추천 조회 API
    description: 같은 부위 중 랜덤으로 최대 3가지 추천
    response:
      '1000':
        description: 성공 - 같은 부위 중 랜덤으로 3가지를 배열로 반환
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  example: 

/app/process/replace/exercise:
  patch:
    tags:
      - Process
    summary: 대체 운동 수정 API
    description: myRoutine에 수정된 걸로 반영
    response:
      '1000':
        description: 수정 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  exapmle:

/app/process/{routineDetailIdx}:
  patch:
    tags:
      - Process
    summary: 운동 스킵 API
    description: 현재 운동은 모두(세트 등) 스킵
    response:
      '1000':
        description: 수정 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  exapmle:

components:
  schemas:
    RoutineCalendar:
      type: object
      properties:
        'monRoutineIdx': 
          type: integer
          example: 32
        'tueRoutineIdx': 
          type: integer
          example: 0
        'wedRoutineIdx': 
          type: integer
          example: 442
        'thuRoutineIdx': 
          type: integer
          example: 0
        'friRoutineIdx': 
          type: integer
          example: 12
        'satRoutineIdx': 
          type: integer
          example: 0
        'sunRoutineIdx': 
          type: integer
          example: 0

    Routine:
      type: array
      items:
        $ref: '#/components/schemas/RoutineDetail'

    RoutineDetail:
      type: object
      properties:
        'healthCategoryIdx':
          type: integer
          example: 2
        'content':
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/RoutineContentA'
              - $ref: '#/components/schemas/RoutineContentB'
      
    RoutineContentA:
      type: object
      properties:
        'rep':
          type: integer
          example: 10
        'weight':
          type: integer
          example: 70

    RoutineContentB:
      type: object
      properties:
        'rep':
          type: integer
          example: 50

    RecRoutineCalendar:
      type: object
      properties:
        'id':
          type: integer
          example: 1
        'item':
          type: array
          items:
            $ref : '#/components/schemas/RecRoutines'

    RecRoutines:
      type: object
      properties:
        'routineIdx':
          type: integer
          example: 121
        'day':
          type: string  
          example: "Monday"
        'parts':
          type: string
          example: "전신"
        'exercises':
          type: array
          items:
            $ref : '#/components/schemas/RecRoutineDetails'

    RecRoutineDetails:
      type: object
      properties:
        'healthCategoryIdx':
          type: integer
          example: 6
        'name':
          type: string
          example: "바벨 로우"
        'set':
          type: integer
          example: 3