tags:
  name: Process
  description: 운동 과정 관련 API - 박준규

/app/process/{routineIdx}:
  get:
    tags:
      - Process
    summary: 운동 루틴 조회 API
    description: 하루의 루틴을 조회하는 API
    parameters:
      - name: routineIdx
        in: path
        required: true
        description: 해당 루틴 Idx를 입력하세요.
        schema:
          type: integer
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  example: true
                'code':
                  type: integer
                  example: 1000
                'message':
                  type: string
                  example: '성공'
                'result':
                  $ref: '#/components/schemas/Routine'
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패

/app/process/before/{routineIdx}:
  get:
    tags:
      - Process
    summary: 운동 시작 전 루틴 조회 API
    description: 세트, 무게, 횟수 확인하는 운동 루틴 세부사항 API
    responses:
      '1000':
        description: 성공 - 총 세트 수와 첫 번째 무게와 횟수를 반환합니다.
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  example: true
                'code':
                  type: integer
                  example: 1000
                'message':
                  type: string
                  example: '성공'
                'result':
                  type: array
                  $ref: '#/components/schemas/RoutineCalendar'
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패

/app/process/detail/{routineIdx}:
  get:
    tags:
      - Process
    summary: 운동 과정 중 루틴 조회 API
    description: 운동 과정 중 현재 진행하는 세트 조회 API
    responses:
      '1000':
        description: 성공 - 총 세트 수와 첫 번째 무게와 횟수를 반환합니다.
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  example: true
                'code':
                  type: integer
                  example: 1000
                'message':
                  type: string
                  example: '성공'
                'result':
                  type: array
                  $ref: '#/components/schemas/RoutineCalendar'
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패

components:
  schemas:
    RoutineCalendar:
      type: object
      properties:
        'monRoutineIdx': 
          type: integer
          example: 32
        'tueRoutineIdx': 
          type: integer
          example: 0
        'wedRoutineIdx': 
          type: integer
          example: 442
        'thuRoutineIdx': 
          type: integer
          example: 0
        'friRoutineIdx': 
          type: integer
          example: 12
        'satRoutineIdx': 
          type: integer
          example: 0
        'sunRoutineIdx': 
          type: integer
          example: 0

    Routine:
      type: array
      items:
        $ref: '#/components/schemas/RoutineDetail'

    RoutineDetail:
      type: object
      properties:
        'healthCategoryIdx':
          type: integer
          example: 2
        'content':
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/RoutineContentA'
              - $ref: '#/components/schemas/RoutineContentB'
      
    RoutineContentA:
      type: object
      properties:
        'rep':
          type: integer
          example: 10
        'weight':
          type: integer
          example: 70

    RoutineContentB:
      type: object
      properties:
        'rep':
          type: integer
          example: 50
