tags:
  name: Dictionary
  description: 운동사전 관련 API

/app/dictionary:
  get:
    summuary: 최근검색, 인기 키워드 조회(각 5개씩)
    params: userIdx
    description: userIdx로 최근검색기록, 인기 키워드 조회하는 api
    tags:
      - Dictionary
    responses:
      '1000':
        description: 성공

/app/dictionary/exerciseinfo:
  get:
    summuary: parts로 운동정보
    params: parts
    description: parts 받아서 그 parts에 포함된 모든 운동 정보(name, muscle, equipment, time, calorie) 조회
    tags:
      - Dictionary
    responses:
      '1000':
        description: 성공

/app/dictionary/exercisemethod:
  get:
    summuary: 운동 name으로 운동방법, 운동주의사항
    params: name
    description: 운동 name받아서 운동방법, 운동주의사항 return
    tags:
      - Dictionary
    responses:
      '1000':
        description: 성공
      '602':
        description: 운동종목을 입력해 주세요


/app/dictionary/exercisechat:
  get:
    summary: 운동 name으로 채팅내역 조회
    parameters:
      - name: name
        in: query
        required: true
        description: 운동 name을 입력하세요.
        schema:
          type: string
    description: 운동 name을 받아서 댓글내용과 댓글 수를 반환합니다.
    tags:
      - Dictionary
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                chatCount:
                  type: integer
                  description: 댓글 수
                comments:
                  type: array
                  items:
                    type: object
                    properties:
                      userIdx:
                        type: integer
                        description: 사용자 인덱스
                      userNickname:
                        type: string
                        description: 사용자 닉네임
                      text:
                        type: string
                        description: 댓글 내용
      '602':
        description: 운동종목을 입력해 주세요


/app/dictionary/chatting:
  post:
    tags:
      - Dictionary
    summuary: 운동 name, userNickname, text post
    description: 운동 name, userNickname, text post해서 db에 넣기
    operationId: postChatting

    requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                userNickname:
                  type: string
                text:
                  type: string

              required:
                - name
                - userNickname
                - text
    responses:
      '1000':
        description: 성공
      '602':
        description: 운동종목을 입력해 주세요
      '603':
        description: 유저 닉네임을 입력해 주세요
      '604':
        description: 댓글내용을 입력해 주세요  
      '4000':
        description: DB error   