tags:
  name: Routine
  description: 루틴 관련 API - 박해승

/app/routine:
  post:
    tags:
      - Routine
    summary: 루틴 생성 API
    description: GPT를 활용하여 루틴을 생성하는 API
    requestBody:
      content:
        application/json:
          schema:
            type: object
            required:
              - RM
              - targets
              - place
              - dayOfWeeks
            properties:
              'RM':
                type: integer
                example: 70
              'targets':
                type: array
                items:
                  type: string
                  example: "shoulder"
              'place':
                type: string
                example: "gym"
              'dayOfWeeks':
                type: array
                items:
                  type: string
                  example: "Monday"
    responses:
      '1000':
        description: 성공 - 생성한 루틴들을 반환해줍니다
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  example: true
                'code':
                  type: integer
                  example: 1000
                'message':
                  type: string
                  example: '성공'
                'result':
                  type: array
                  items: 
                    $ref : '#/components/schemas/RecRoutineCalendar'

/app/routine/calendar:
  post:
    tags:
      - Routine
    summary: 루틴 일정 등록 API
    description: 루틴 생성을 통해 추천 받은 루틴 Idx를 통해 주간 루틴 일정을 등록하는 API
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RoutineCalendar'
    responses:
      '1000':
        description: 성공 - 각 요일별 루틴 Idx 값을 통해 수정합니다. 
  get:
    tags:
      - Routine
    summary: 루틴 일정 조회 API
    description: 주간 루틴 일정을 조회하는 API
    responses:
      '1000':
        description: 성공 - 각 요일별로 존재하는 루틴의 Idx 값을 반환해줍니다
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  example: true
                'code':
                  type: integer
                  example: 1000
                'message':
                  type: string
                  example: '성공'
                'result':
                  $ref: '#/components/schemas/RoutineCalendar'
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패
  put:
    tags:
      - Routine
    summary: 루틴 일정 수정 API
    description: 주간 루틴 일정을 수정하는 API
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RoutineCalendar'
    responses:
      '1000':
        description: 성공 - 각 요일별 루틴 Idx 값을 통해 수정합니다. 

/app/routine/{routineIdx}:
  get:
    tags:
      - Routine
    summary: 루틴 조회 API
    description: 하루의 루틴을 조회하는 API
    parameters:
      - name: routineIdx
        in: path
        required: true
        description: 해당 루틴 Idx를 입력하세요.
        schema:
          type: integer
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  example: true
                'code':
                  type: integer
                  example: 1000
                'message':
                  type: string
                  example: '성공'
                'result':
                  $ref: '#/components/schemas/Routine'
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패

  put:
    tags:
      - Routine
    summary: 루틴 수정 API
    description: 루틴을 수정하는 API
    parameters:
      - name: routineIdx
        in: path
        required: true
        description: 해당 루틴 Idx를 입력하세요.
        schema:
          type: integer
    requestBody:
      content:
        application/json:
          schema:
            type: array
            required:
              - healthCategoryIdx
              - content
            items:
              properties:
                'healthCategoryIdx':
                  type: integer
                  example: 2
                'content':
                  type: array
                  items:
                    properties:
                      'rep':
                        type: integer
                        example: 10
                      'weight':
                        type: integer
                        example: 100
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  example: true
                'code':
                  type: integer
                  example: 1000
                'message':
                  type: string
                  example: '성공'
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패

  delete:
    tags:
      - Routine
    summary: 루틴 삭제 API
    description: 루틴을 삭제하는 API
    parameters:
      - name: routineIdx
        in: path
        required: true
        description: 해당 루틴 Idx를 입력하세요.
        schema:
          type: integer
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                'isSuccess':
                  type: boolean
                  example: true
                'code':
                  type: integer
                  example: 1000
                'message':
                  type: string
                  example: '성공'
      '2000':
        description: JWT 토큰을 입력해주세요
      '3000':
        description: JWT 토큰 검증 실패

components:
  schemas:
    RoutineCalendar:
      type: object
      properties:
        'monRoutineIdx': 
          type: integer
          example: 32
        'tueRoutineIdx': 
          type: integer
          example: 0
        'wedRoutineIdx': 
          type: integer
          example: 442
        'thuRoutineIdx': 
          type: integer
          example: 0
        'friRoutineIdx': 
          type: integer
          example: 12
        'satRoutineIdx': 
          type: integer
          example: 0
        'sunRoutineIdx': 
          type: integer
          example: 0

    Routine:
      type: array
      items:
        $ref: '#/components/schemas/RoutineDetail'

    RoutineDetail:
      type: object
      properties:
        'healthCategoryIdx':
          type: integer
          example: 2
        'exerciseName':
          type: string
          example: 인클라인 덤벨프레스
        'content':
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/RoutineContentA'
              - $ref: '#/components/schemas/RoutineContentB'
      
    RoutineContentA:
      type: object
      properties:
        'rep':
          type: integer
          example: 10
        'weight':
          type: integer
          example: 70

    RoutineContentB:
      type: object
      properties:
        'rep':
          type: integer
          example: 50

    RecRoutineCalendar:
      type: object
      properties:
        'id':
          type: integer
          example: 1
        'item':
          type: array
          items:
            $ref : '#/components/schemas/RecRoutines'

    RecRoutines:
      type: object
      properties:
        'routineIdx':
          type: integer
          example: 121
        'day':
          type: string  
          example: "Monday"
        'parts':
          type: string
          example: "전신"
        'exercises':
          type: array
          items:
            $ref : '#/components/schemas/RecRoutineDetails'

    RecRoutineDetails:
      type: object
      properties:
        'healthCategoryIdx':
          type: integer
          example: 6
        'name':
          type: string
          example: "바벨 로우"
        'set':
          type: integer
          example: 3