openapi: 3.0.0
info:
  title: "gptHealth"
  version: "1.0.0"
tags:
  - name: User
    description: 사용자 관련 API
paths:
  /app/user:
    post:
      tags:
        - User
      summary: 회원가입 API
      operationId: postUsers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                userPw:
                  type: string
                userNickname:
                  type: string
                gender:
                  type: number
                height:
                  type: number
                weight:
                  type: number
                birthYear:
                  type: number
              required:
                - userId
                - userPw
                - userNickname
                - gender
                - height
                - weight
                - birthYear
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        '400':
          description: 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: JWT 토큰을 입력해주세요.
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 4001
                  message:
                    type: string
                    example: 서버 에러

    delete:
      tags:
        - User
      summary: 회원탈퇴 API
      description: 회원탈퇴하는 API로 바로 회원 탈퇴되니까 주의해서 사용해야함.
      responses:
        '1000':
          description: 성공

  /app/user/login:
    post:
      tags:
        - User
      summary: 로그인 API
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                userPw:
                  type: string
              required:
                - userId
                - userPw
      responses:
        '1000':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  accessToken:
                    type: string
                    example: [생성된 액세스 토큰]
        '400':
          description: 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 3000
                  message:
                    type: string
                    example: JWT 토큰 검증 실패
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 4001
                  message:
                    type: string
                    example: 서버 에러

  /app/user/check:
    post:
      tags:
        - User
      summary: 토큰 체크 API
      description: jwt access token을 체크하는 API
      responses:
        '1000':
          description: 성공
          content:
            application/json1:
              schema:
                type: object
                properties:
                  'isSuccess':
                    type: boolean
                    example: true
                  'code':
                    type: integer
                    example: 1000
                  'message':
                    type: string
                    example: '성공'
                  'result':
                    type: object
                    properties:
                      accessToken:
                        type: string
                        example: 생성된 액세스 토큰
            application/json2:
              schema:
                type: object
                properties:
                  'isSuccess':
                    type: boolean
                    example: true
                  'code':
                    type: integer
                    example: 1000
                  'message':
                    type: string
                    example: '성공'
        '3000':
          description: JWT 토큰 검증 실패
        '4001':
          description: 서버 에러

/app/user/device:
  put:
    summary: 가장 최근 로그인한 디바이스토큰 db에 저장 api
    description: 로그인할 떄 userId로 deviceToken 저장
    tags:
      - User
    parameters:
      - name: devToken
        in: query
        required: true
        description: 최근 로그인 기기의 디바이스토큰
        schema:
          type: string
    responses:
      '1000':
        description: 성공
      '2019':
        description: 로그인한 기기의 디바이스토큰값을 입력해주세요.
