tags:
  name: User
  description: 사용자 관련 API

/app/test:
  get:
    summary: 테스트 API
    description: 서버 응답을 테스트하는 API
    tags:
      - User
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                isSuccess:
                  type: boolean
                  example: true
                code:
                  type: integer
                  example: 1000
                message:
                  type: string
                  example: 성공

/app/users:
  get:
    summary: 유저 조회 API
    description: 파라미터 값으로 유저를 조회하는 API
    tags:
      - User
    parameters:
      - name: email
        in: query
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                isSuccess:
                  type: boolean
                  example: true
                code:
                  type: integer
                  example: 1000
                message:
                  type: string
                  example: 성공
                result:
                  type: array
                  items:
                    type: object
                    properties:
                      email:
                        type: string
                        example: phs@naver.com
                      userNickName:
                        type: string
                        example: 승

                  
      '3003':
        description: 존재하지 않는 이메일입니다.


