openapi: 3.0.0
info:
  title: "gptHealth"
  version: "1.0.0"
tags:
  - name: User
    description: 사용자 관련 API
paths:
  /app/users:
    post:
      tags:
        - User
      summary: 회원가입 API
      operationId: postUsers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                userPw:
                  type: string
                userNickname:
                  type: string
                gender:
                  type: number
                height:
                  type: number
                weight:
                  type: number
                birthYear:
                  type: number
              required:
                - userId
                - userPw
                - userNickname
                - gender
                - height
                - weight
                - birthYear
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        '400':
          description: 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: JWT 토큰을 입력해주세요.
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 4001
                  message:
                    type: string
                    example: 서버 에러

  /app/login:
    post:
      tags:
        - User
      summary: 로그인 API
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                userPw:
                  type: string
              required:
                - userId
                - userPw
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        '400':
          description: 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 3000
                  message:
                    type: string
                    example: JWT 토큰 검증 실패
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 4001
                  message:
                    type: string
                    example: 서버 에러
