tags:
  name: Mypage
  description: 마이페이지 관련 API

/app/mypage:
  get:
    summary: API NO.1 - 해당 month에 운동한 모든 날짜 반환 api
    parameters:
      - name: month
        in: query
        required: true
        description: month를 입력하세요.
        schema:
          type: integer
    description: month 받아서 쿠키에 가지고 있는 토큰(유저)가 그 month에 운동한 날짜 반환합니다.
    tags:
      - Mypage
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                result:
                  type: array
                  items:
                    type: string
                  description: 유저가 운동한 날짜 목록
      '502':
        description: month를 입력해 주세요

/app/mypage/exercise:
  get:
    summary: API NO.2 - exerciseinfo 조회 api
    parameters:
      - name: date
        in: query
        require: true
        description: 조회 날짜(YYYYMMDD 형식)
        schema:
          type: integer
    description: 운동했던 기록들을 조회하는 api
    tags:
      - Mypage
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                isSuccess:
                  type: boolean
                  description: 성공 여부
                  example: true
                code:
                  type: integer
                  description: 응답 코드
                  example: 1000
                message:
                  type: string
                  description: 응답 메시지
                  example: 성공
                result:
                  type: object
                  properties:
                    exercise:
                      type: array
                      description: 운동 목록
                      items:
                        type: string
                        example: ["데드리프트", "풀업"]
                  totalCalories:
                    type: integer
                    description: 총 칼로리
                  totalWeight:
                    type: integer
                    description: 총 무게
                  totalTime:
                    type: integer
                    description: 총 시간(초 단위)
                  totalDist:
                    type: integer
                    description: 총 거리
      '708':
        description: 날짜형식을 YYYYMMDD 형식으로 입력해주세요.
      '709':
        description: 해당 날짜에 routine이 등록(기록)되지 않았습니다.

/app/mypage/record:
  get:
    summary: API NO.3 - 모든 운동 데이터 조회 api
    description: 주차별 운동 기록 데이터 모두 조회
    tags:
      - Mypage
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                result:
                  exerciseRecord:
                    type: array
                    items:
                      type: object
                      properties:
                        weekNumer:
                          type: string
                          description: 주차 정보 ex) 8월 1째 주
                        weeklyExerciseTime:
                          type: integer
                          description: 주간 운동 시간(초 단위)
                        weeklyCalories:
                          type: integer
                          description: 주간 소모 칼로리
      # '502':
      #   description: 달을 입력해주세요.


/app/mypage/userinfo:
  get:
    summary: API NO.4 - userinfo 조회 api
    description: 쿠키에 가지고 있는 토큰(유저)으로 userinfo 반환하는 api
    tags:
      - Mypage
    responses:
      '1000':
        description: 성공
        content:
          application/json:
            schema:
              type: object
              properties:
                result:
                  type: array
                  items:
                    type: string
                  description: 유저info

/app/mypage/updateuser:
  put:
    summary: API NO.5 - userNickname 수정 api
    description: 쿠키에 가지고 있는 토큰(유저)으로 userNickname 수정하는 api
    tags:
      - Mypage
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              userNickname:
                type: string
                example: 초코맛 프로틴
                description: 수정할 유저 닉네임
    responses:
      '1000':
        description: 성공
      '701':
        description: 수정할 유저 닉네임을 입력해 주세요.


/app/mypage/nickname:
  get:
    summary: API NO.6 - 닉네임 변경할때 중복 닉네임 있는지 검사하는 api
    parameters:
      - name: userNickName
        in: query
        required: true
        description: 수정할 userNickname을 입력하세요.
        schema:
          type: string
    description: userNickname 입력에 따라 닉네임 변경할 때 중복 닉네임 있는지 검사함.(true-닉네임 있음. fasle-닉네임 없음->입력한 닉네임으로 수정 가능)
    tags:
      - Mypage
    responses:
      '1000':
        description: 성공
      '706':
        description: 수정할 userNickname을 입력해 주세요.  
      '3003':
        description: 수정할 userNickname과 동일한 userNickname이 존재합니다.

/app/mypage/updatepwd:
  put:
    summary: API NO.7 - userPw 수정 api(기존 비밀번호와 같으면 수정x)
    description: 쿠키에 가지고 있는 토큰(유저)으로 userPw 수정하는 api
    tags:
      - Mypage
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              userPw:
                type: string
    responses:
      '1000':
        description: 성공
      '703':
        description: 수정할 유저 패스워드를 입력해 주세요.
      '704':
        description: 수정할 userPw와 기존 userPw가 동일합니다.
      
/app/mypage/comparepwd:
  post:
    summary: API NO.8 - userPw 확인 api(기존 비밀번호와 같은지 여부)
    description: 쿠키에 가지고 있는 토큰(유저)으로 userPw 확인하는 api
    tags:
      - Mypage
    requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userPw:
                  type: string
    responses:
      '706':
        description: 입력한 userPw와 기존 userPw가 동일합니다.(true)
      '707':
        description: 입력한 userPw와 기존 userPw가 동일하지 않습니다.(false)

/app/mypage/coupon:
  post:
    summary: 쿠폰 코드 등록 api
    description: 쿠폰 코드를 등록하는 aapi
    tags:
      - Mypage
    requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
    responses:
      '1000':
        description: 성공
      '910':
        description: 유효하지 않은 쿠폰 코드입니다.
      '911':
        description: 이미 사용한 코드입니다.
      '912':
        description: 코드가 기간 만료되었습니다.
      '4002':
        description: 통신 오류

/app/mypage/isalarm:
  get:
    summary: 알림 수신 여부 확인 api
    description: 알림 수신 여부를 확인하는 api
    tags:
      - Mypage
    responses:
      '1000':
        content:
          application/json:
            schema:
              type: object
              properties:
                isSuccess:
                  type: boolean
                  example: true
                code:
                  type: integer
                  example: 1000
                message:
                  type: string
                  example: 성공
                result:
                  type: object
                  properties:
                    isAlarm:
                      type: boolean
                      example: true
      '4002':
        description: 통신 오류
  put:
    summary: 알림 수신 여부 변경 api
    description: 알림 수신 여부를 변경하는 api (기존의 여부와 반대로 자동 적용)
    tags:
      - Mypage
    responses:
      '1000':
        description: 성공
      '4002':
        description: 통신 오류

/app/mypage/alarm:
  post:
    summary: 알림 내용 저장 api
    description: 알림을 송신한 내용을 저장하는 api
    tags:
      - Mypage
    requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  example: "TEST"
    responses:
      '1000':
        description: 성공
      '4002':
        description: 통신 오류
  get:
    summary: 알림 내역 조회 api
    description: 알림을 수신한 내역을 조회하는 api
    tags:
      - Mypage
    responses:
      '1000':
        content:
          application/json:
            schema:
              type: object
              properties:
                isSuccess:
                  type: boolean
                  example: true
                code:
                  type: integer
                  example: 1000
                message:
                  type: string
                  example: 성공
                result:
                  type: array
                  items:
                    type: object
                    properties:
                      content:
                        type: string
                        example: "TEST"
                      diff:
                        type: string
                        example: "1일전"
      '4002':
        description: 통신 오류